# Generated by Django 4.1 on 2022-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.IntegerField(max_length=6),
        ),
    ]
