# Generated by Django 4.1 on 2022-08-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='marital_status',
        ),
    ]
