# Generated by Django 4.1 on 2022-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_customer_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('a', 'Married'), ('b', 'Single'), ('b', 'Others')], default=2, max_length=15),
            preserve_default=False,
        ),
    ]
