# Generated by Django 4.1 on 2022-08-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_customer_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
